package Constructor;

/* Compiler is responsible to generate default constructor(But not JVM)
   If we are not writing any constructor then only compiler ll generate default constructor
 .i.e if we are writing at least one constructor then compiler wont generate any default constructor.
 Hence every class in java can contain constructors , it may be default constructor generated by compiler
 or customized constructor explicitly provided by programmer but not both simultaneously.*/

public class Defaultconstructor {


}
